name: CLI Build

on:
  push:
    branches: [ master ]
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./theseus_cli
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Get build cache
        id: cache-build
        uses: actions/cache@v2
        with:
          path: ../target/**
          key: ${{ runner.os }}-build-cache
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Build program
        with:
          command: build