name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for CF Pages
        id: cf-pages
        uses: WalshyDev/cf-pages-await@v1
        with:
          project: 'omorphia'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: '9ddae624c98677d68d93df6e524a6061'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commitHash: ${{ steps.push-changes.outputs.commit-hash }}
